### ISSUE TITLE
Abort Trap 6 when compiling CM file on MAC OS X 10.10.3

### ISSUE THREAD

**Issue by lcj005** [rlaager/docsis#15]
When creating a cm.bin file on MAC OS X 10.10.3 I get the following:

JonesyMacBookPro:Downloads cjones$ docsis -e CM.txt key CM,bin
Abort trap: 6
JonesyMacBookPro:Downloads cjones$ 

MAC generates a crash dump which I can send on request.

**Comment by AdrianSimionov** [comment]
Chris, is this for every CM you try to encode or for a specific one?
I would like to have the TXT version of the file. I do not have constrains on the data so if you have in the TXT version something out of the specs, it should crash with a memory dump.

**Comment by lcj005** [comment]
Hi Adrian,

Attached is the file I am trying to build. I also include the crash dump from the MAC OS.

Cheers,

Chris
On 24 Mar 2015, at 16:39, Adrian Simionov <notifications@github.com> wrote:

Chris, is this for every CM you try to encode or for a specific one?
I would like to have the TXT version of the file. I do not have constrains on the data so if you have in the TXT version something out of the specs, it should crash with a memory dump.

—
Reply to this email directly or view it on GitHub <https://github.com/rlaager/docsis/issues/15#issuecomment-85591735>.


Main
{
	NetworkAccess 1;
	MaxCPE 16;
	SwUpgradeServer 192.168.52.240;
	/* SwUpgradeFilename "TS090167_SIP.img"; */ 
	SwUpgradeFilename "TS090175A_031215_SIP.img";
	SnmpMibObject ifAdminStatus.1 Integer 1; /* up */
	SnmpMibObject ifAdminStatus.16 Integer 1; /* up */
	SnmpMibObject docsDevSwAdminStatus.0 Integer 2; /* allowProvisioningUpgrade */
	MfgCVCData 0x3082037a30820262a00302010202107d833efc5265959edd6c066ff4c5e977300d06092a864886f70d0101050500306f310b3009060355040613024245311f301d060355040a131674436f6d4c616273202d204575726f2d444f4353495331153013060355040b130c4361626c65204d6f64656d73312830260603550403131f4575726f2d444f43534953204361626c65204d6f64656d20526f6f74204341301e170d3133313032393030303030305a170d3233313032383233353935395a3067310b3009060355040613025553311a3018060355040a131141525249532047726f75702c20496e632e31143012060355040b130b4575726f2d444f4353;
	MfgCVCData 0x4953312630240603550403131d436f646520566572696669636174696f6e20436572746966696361746530820122300d06092a864886f70d01010105000382010f003082010a0282010100bc74f65f642aeb0e5ac47734f8d7c0e66c2452482061b6727146472d9e9cda7a8d265df86106f4cda505f3fdbc57eea0835c16a3da06b674a65940dee80ea6c7dfe6232386105df8495ef57ef3d5c9333d41ac97559416ff40f775d410677bafd556ba9af7cf4c676c61a44b665fad74434b067175457b1ddf23eed35726a0099b1901f13d70edcb9c60bcf041d2ffc7b324f36da2e022b2a3983a96d1de19e5801be52ba1894f6906588d158a44d2a2774231;
	MfgCVCData 0xce6390029766874bf85391737fc2ecad6ff63ff961abf77d8b638446ed42c54740a1ef9106cdb4dbb4fad39a8529046b51ce8dd4ba665c57f3c841be91b2dd018b0bc85e5caab4e8fae0b292ef0203010001a31a301830160603551d250101ff040c300a06082b06010505070303300d06092a864886f70d010105050003820101008a134540ca5653f20be6f5cb053b061d0418b3bd018720fe609e9820bc11852c8b4d71e6cde11dfdf5a66817124228596f4a9fb771a64df681bd0f9018ddfe6979589a8d8303d74aa491b2830232f5a02a52e164c3fb8006870f61018b1e4f00706e3c910887ef04dae9029fbfb3cc98fe52afde5d2d88be3e3078e3;
	MfgCVCData 0x288e51940b1e1cc4fd3cfcb72fcc2ed1d7a2d549a7db42e5d97ffa719c621e170d9b9b0394178471ca0ce5bed664981b24781cc407423bcfa42c566f036a16b746820667bb168788cc49fb3d1df9f7ef9e62b8e0b90b44493c69c396fc3170b6db23cef7fe8ab37cc347243874368d45d877c845db98c0e4a6d009df9c884a4f4bb3249b;
	GlobalPrivacyEnable 1;
	SnmpMibObject docsDevNmAccessCommunity.1 String "public" ;
	SnmpMibObject arrisMtaDevProvMethodIndicator.0 Integer 4; /* gupi */
	SnmpMibObject docsDevNmAccessControl.1 Integer 2; /* read */
	SnmpMibObject docsDevNmAccessInterfaces.1 HexString 0x4000 ;
	SnmpMibObject docsDevNmAccessIp.1 IPAddress 255.255.255.255 ;
	SnmpMibObject docsDevNmAccessIpMask.1 IPAddress 255.255.255.255 ;
	SnmpMibObject docsDevNmAccessStatus.1 Integer 4; /* createAndGo */
	SnmpMibObject docsDevNmAccessCommunity.2 String "private" ;
	SnmpMibObject docsDevNmAccessControl.2 Integer 3; /* readWrite */
	SnmpMibObject docsDevNmAccessInterfaces.2 HexString 0x4000 ;
	SnmpMibObject docsDevNmAccessIp.2 IPAddress 255.255.255.255 ;
	SnmpMibObject docsDevNmAccessIpMask.2 IPAddress 255.255.255.255 ;
	SnmpMibObject docsDevNmAccessStatus.2 Integer 4; /* createAndGo */
	GenericTLV TlvCode 202 TlvLength 3 TlvValue 0x010103;
	SnmpMibObject arrisCmDoc30AccessTelnetEnable.0 Integer 1; /* enable */
	SnmpMibObject arrisRouterDSLiteWanEnable.0 Integer 2; /* false */
	SnmpMibObject arrisCmDoc30AccessHttpLan.0 Integer 1; /* enable */
	SnmpMibObject arrisCmDoc30AccessHttpWan.0 Integer 1; /* enable */
	SnmpMibObject arrisCmDoc30AccessClientSeed.0 HexString 0x0a7c46132a02b29e;
	SnmpMibObject arrisRouterCustomID.0 Integer 7 ; 
        SnmpMibObject arrisRouterWebAccessPage.1.1 String "skin:lgi" ;
	UsServiceFlow
	{
		UsServiceFlowRef 1;
		QosParamSetType 7;
		ServiceClassName "mercury_up";
	}
	DsServiceFlow
	{
		DsServiceFlowRef 2;
		QosParamSetType 7;
		ServiceClassName "mercury_down";
	}
	DsServiceFlow
	{
		DsServiceFlowRef 3;
		QosParamSetType 7;
		TrafficPriority 6;
		MaxRateSustained 20000;
		MaxTrafficBurst 8000;
		MinReservedRate 0;
	}
	UsServiceFlow
	{
		UsServiceFlowRef 4;
		QosParamSetType 7;
		TrafficPriority 6;
		MaxRateSustained 20000;
		MaxTrafficBurst 8000;
		MinReservedRate 0;
		MaxConcatenatedBurst 1522;
		SchedulingType 2;
		RequestOrTxPolicy 0x00000060;
	}
	DsPacketClass
	{
		ClassifierRef 1;
		ServiceFlowRef 3;
		RulePriority 2;
		ActivationState 1;
		IpPacketClassifier
		{
			DstPortStart 5060;
			DstPortEnd 5060;
		}
	}
	UsPacketClass
	{
		ClassifierRef 2;
		ServiceFlowRef 4;
		RulePriority 2;
		ActivationState 1;
		LLCPacketClassifier
		{
			EtherType 0x030f16;
		}
	}
	UsPacketClass
	{
		ClassifierRef 3;
		ServiceFlowRef 4;
		RulePriority 2;
		ActivationState 1;
		IpPacketClassifier
		{
			SrcPortStart 5060;
			SrcPortEnd 5060;
		}
	}
	/* CmMic b386408449a657fc4e1cb5020968cf09; */
	/* CmtsMic b83f9541cbea278a663ed9f14c8437fa; */
	/*EndOfDataMkr*/

}

**Comment by lcj005** [comment]
Adrian,

I've fixed this. I needed to reinstall net-snmp on my mac, as it was this that was broken.
Now I've done this, the DOCSIS tool now works.

**Comment by AdrianSimionov** [comment]
Wonderful Chris, thanks a lot for letting us know.
