### ISSUE TITLE
Trying to compile on cygwin and get "undefined reference errors"

### ISSUE THREAD

**Issue by wzapar00** [rlaager/docsis#20]
Can someone please help me out.  I am trying to compile on cygwin and I keep getting the following errors.

docsis.o: In function `encode_one_file':
/cygdrive/c/brett_docsis/docsis/src/docsis.c:340: undefined reference to `__stack_chk_guard'
/cygdrive/c/brett_docsis/docsis/src/docsis.c:405: undefined reference to `__stack_chk_guard'
/cygdrive/c/brett_docsis/docsis/src/docsis.c:405: undefined reference to `__stack_chk_fail'
docsis.o: In function `main':
/cygdrive/c/brett_docsis/docsis/src/docsis.c:177: undefined reference to `__stack_chk_guard'
/cygdrive/c/brett_docsis/docsis/src/docsis.c:336: undefined reference to `__stack_chk_guard'
/cygdrive/c/brett_docsis/docsis/src/docsis.c:336: undefined reference to `__stack_chk_fail'
docsis_encode.o: In function `encode_ip6':
/cygdrive/c/brett_docsis/docsis/src/docsis_encode.c:211: undefined reference to `__stack_chk_guard'
/cygdrive/c/brett_docsis/docsis/src/docsis_encode.c:237: undefined reference to `__stack_chk_guard'
/cygdrive/c/brett_docsis/docsis/src/docsis_encode.c:237: undefined reference to `__stack_chk_fail'
docsis_encode.o: In function `encode_ip6_list':
/cygdrive/c/brett_docsis/docsis/src/docsis_encode.c:240: undefined reference to `__stack_chk_guard'
/cygdrive/c/brett_docsis/docsis/src/docsis_encode.c:265: undefined reference to `__stack_chk_guard'
/cygdrive/c/brett_docsis/docsis/src/docsis_encode.c:265: undefined reference to `__stack_chk_fail'
docsis_encode.o: In function `encode_ip6_prefix_list':
/cygdrive/c/brett_docsis/docsis/src/docsis_encode.c:268: undefined reference to `__stack_chk_guard'
/cygdrive/c/brett_docsis/docsis/src/docsis_encode.c:299: undefined reference to `__stack_chk_guard'
/cygdrive/c/brett_docsis/docsis/src/docsis_encode.c:299: undefined reference to `__stack_chk_fail'
docsis_encode.o: In function `encode_ip_ip6':
/cygdrive/c/brett_docsis/docsis/src/docsis_encode.c:302: undefined reference to `__stack_chk_guard'
/cygdrive/c/brett_docsis/docsis/src/docsis_encode.c:321: undefined reference to `__stack_chk_guard'
/cygdrive/c/brett_docsis/docsis/src/docsis_encode.c:321: undefined reference to `__stack_chk_fail'
docsis_encode.o: In function `encode_char_ip_ip6':
/cygdrive/c/brett_docsis/docsis/src/docsis_encode.c:324: undefined reference to `__stack_chk_guard'
/cygdrive/c/brett_docsis/docsis/src/docsis_encode.c:348: undefined reference to `__stack_chk_guard'
/cygdrive/c/brett_docsis/docsis/src/docsis_encode.c:348: undefined reference to `__stack_chk_fail'
docsis_encode.o: In function `encode_ip_ip6_port':
/cygdrive/c/brett_docsis/docsis/src/docsis_encode.c:351: undefined reference to `__stack_chk_guard'
/cygdrive/c/brett_docsis/docsis/src/docsis_encode.c:387: undefined reference to `__stack_chk_guard'
/cygdrive/c/brett_docsis/docsis/src/docsis_encode.c:387: undefined reference to `__stack_chk_fail'
docsis_decode.o: In function `decode_ip6':
/cygdrive/c/brett_docsis/docsis/src/docsis_decode.c:121: undefined reference to `__stack_chk_guard'
/cygdrive/c/brett_docsis/docsis/src/docsis_decode.c:132: undefined reference to `__stack_chk_guard'
/cygdrive/c/brett_docsis/docsis/src/docsis_decode.c:132: undefined reference to `__stack_chk_fail'
docsis_decode.o: In function `decode_ip6_list':
/cygdrive/c/brett_docsis/docsis/src/docsis_decode.c:135: undefined reference to `__stack_chk_guard'
/cygdrive/c/brett_docsis/docsis/src/docsis_decode.c:148: undefined reference to `__stack_chk_guard'
/cygdrive/c/brett_docsis/docsis/src/docsis_decode.c:148: undefined reference to `__stack_chk_fail'
docsis_decode.o: In function `decode_ip6_prefix_list':
/cygdrive/c/brett_docsis/docsis/src/docsis_decode.c:151: undefined reference to `__stack_chk_guard'
/cygdrive/c/brett_docsis/docsis/src/docsis_decode.c:163: undefined reference to `__stack_chk_guard'
/cygdrive/c/brett_docsis/docsis/src/docsis_decode.c:163: undefined reference to `__stack_chk_fail'
docsis_decode.o: In function `decode_ip_ip6':
/cygdrive/c/brett_docsis/docsis/src/docsis_decode.c:166: undefined reference to `__stack_chk_guard'
/cygdrive/c/brett_docsis/docsis/src/docsis_decode.c:178: undefined reference to `__stack_chk_guard'
/cygdrive/c/brett_docsis/docsis/src/docsis_decode.c:178: undefined reference to `__stack_chk_fail'
docsis_decode.o: In function `decode_char_ip_ip6':
/cygdrive/c/brett_docsis/docsis/src/docsis_decode.c:181: undefined reference to `__stack_chk_guard'
/cygdrive/c/brett_docsis/docsis/src/docsis_decode.c:193: undefined reference to `__stack_chk_guard'
/cygdrive/c/brett_docsis/docsis/src/docsis_decode.c:193: undefined reference to `__stack_chk_fail'
docsis_decode.o: In function `decode_ip_ip6_port':
/cygdrive/c/brett_docsis/docsis/src/docsis_decode.c:196: undefined reference to `__stack_chk_guard'
/cygdrive/c/brett_docsis/docsis/src/docsis_decode.c:208: undefined reference to `__stack_chk_guard'
/cygdrive/c/brett_docsis/docsis/src/docsis_decode.c:208: undefined reference to `__stack_chk_fail'
docsis_decode.o: In function `decode_unknown':
/cygdrive/c/brett_docsis/docsis/src/docsis_decode.c:372: undefined reference to `__stack_chk_guard'
/cygdrive/c/brett_docsis/docsis/src/docsis_decode.c:405: undefined reference to `__stack_chk_guard'
/cygdrive/c/brett_docsis/docsis/src/docsis_decode.c:405: undefined reference to `__stack_chk_fail'
docsis_snmp.o: In function `decode_vbind':
/cygdrive/c/brett_docsis/docsis/src/docsis_snmp.c:283: undefined reference to `__stack_chk_guard'
/cygdrive/c/brett_docsis/docsis/src/docsis_snmp.c:626: undefined reference to `__stack_chk_guard'
/cygdrive/c/brett_docsis/docsis/src/docsis_snmp.c:626: undefined reference to `__stack_chk_fail'
docsis_snmp.o: In function `encode_vbind':
/cygdrive/c/brett_docsis/docsis/src/docsis_snmp.c:34: undefined reference to `__stack_chk_guard'
/cygdrive/c/brett_docsis/docsis/src/docsis_snmp.c:278: undefined reference to `__stack_chk_guard'
/cygdrive/c/brett_docsis/docsis/src/docsis_snmp.c:278: undefined reference to `__stack_chk_fail'
docsis_yy.o: In function `create_external_file_tlv':
/cygdrive/c/brett_docsis/docsis/src/docsis_yy.y:426: undefined reference to `__stack_chk_guard'
/cygdrive/c/brett_docsis/docsis/src/docsis_yy.y:457: undefined reference to `__stack_chk_guard'
/cygdrive/c/brett_docsis/docsis/src/docsis_yy.y:457: undefined reference to `__stack_chk_fail'
hmac_md5.o: In function `hmac_md5':
/cygdrive/c/brett_docsis/docsis/src/hmac_md5.c:57: undefined reference to `__stack_chk_guard'
/cygdrive/c/brett_docsis/docsis/src/hmac_md5.c:122: undefined reference to `__stack_chk_guard'
/cygdrive/c/brett_docsis/docsis/src/hmac_md5.c:122: undefined reference to `__stack_chk_fail'
collect2: error: ld returned 1 exit status
Makefile:415: recipe for target 'docsis.exe' failed
make[2]: *** [docsis.exe] Error 1
make[2]: Leaving directory '/cygdrive/c/brett_docsis/docsis/src'
Makefile:473: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/cygdrive/c/brett_docsis/docsis'
Makefile:367: recipe for target 'all' failed
make: *** [all] Error 2

Regards,

Will

**Comment by AdrianSimionov** [comment]
As I mentioned before, Windows is not tested.
I do not own a windows machine to be able to troubleshoot this.

**Comment by wzapar00** [comment]
This seems related to how gcc links.  Suggestions are an addition to configure.in with the following gcc flag added "-fno-stack-protector" \" to disable these warnings which crash the compiler.  Again this is Redhat Cygwin and should build just like Redhat.  I have never had problems building anything with gcc on Cygwin, including net-snmp.  Thanks again.

**Comment by wzapar00** [comment]
One other thing too.  configure.in is no longer supported.  It should be renamed configure.ac.

**Comment by AdrianSimionov** [comment]
Can you please confirm that adding this flag resolves the issue?
For configure.in I will open a new bug, let's try to stay organized.

**Comment by KvalheimRacing** [comment]
@wzapar00 how did you fix this? The flag u mentioned did not work for me, still get undefined reference

**Comment by KvalheimRacing** [comment]
Lol, I figured it out, I was not including all the .cpp files I used when I was compiling. So 100% user fault lol
