### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by ryandesign** [rlaager/docsis#21]
Hello, I'm a developer with the MacPorts package management system. We were [recently asked](https://trac.macports.org/ticket/49268) to add docsis 0.9.6 to MacPorts, which I've now done. The build failed for two different reasons. These problems have apparently been fixed in your repository years ago, but were never released, so I had to find the fixes and backport them to 0.9.6. Perhaps you could release a new version of docsis?

**Comment by rapgro** [comment]
:+1:

**Comment by AdrianSimionov** [comment]
Ryan, I did the request as I had many requests for people I know to have it in MacPorts.

Me and Richard, we never released an official version, is it possible to include in MacPorts the master tree of this repository? I know it works without problems under OSX and it includes a lot of new fixes and features.

In Fedora there was no problem to have the build made from master without an official release here, I do not know how it works in MacPorts.

**Comment by AdrianSimionov** [comment]
Well, after 5 years I think it was time to have a stable release. I just created 0.9.8.
Let me know if we can close this issue.
