### ISSUE TITLE
Bug compiling MTA

### ISSUE THREAD

**Issue by julianeble** [rlaager/docsis#23]
Hello,

I don't know why but when I do compile the MTA with docsis -p or docsis -na -p, the provisioning just don't work.
It says something about pktcMtaDevEnabled inhexistent.

[WARNING] [PACM.PROVISION(pid=1958)]: added Error OID (null)/Unsupported OID (1.3.6.1.2.1.140.1.1.6.0)
[INFO] [PACM.SNMP(pid=1958)]: Populate Error OID 1.3.6.1.2.1.140.1.1.6.0 value=(null) reason=Unsupported OID
[WARNING] [PACM.PROVISION(pid=1958)]: added Error OID (null)/Unsupported OID (1.3.6.1.2.1.140.1.1.6.0)
[INFO] [PACM.SNMP(pid=1958)]: Populate Error OID 1.3.6.1.2.1.140.1.1.6.0 value=(null) reason=Unsupported OID
[WARNING] [PACM.CFM(pid=530)]: provStat != CFM OK. setting return code to pass with warning

When I do the same configuration, on a docsis version 0.9.6 it works perfectly

**Comment by AdrianSimionov** [comment]
Please attach the text file, the binary file created with 0.9.6 which is working and the binary created with the master tree from GitHub.

Which provisioning method are you using? Is a PacketCable or EuPacketCable environment?

Hash string is not necessary present in every provisioning method and should match the EU-PC or NA-PC load from the modem.

**Comment by julianeble** [comment]
Hello Adrian,

I'm using Packet Cable.
I aware about the hash, and I did that doing sha1sum and also by applying the command -na to be sure.
And same happen.

Below are the files:
https://www.dropbox.com/sh/di216yi63nh81h7/AADJjebt5qo4zvGsQiEqiWBBa?dl=0

**Comment by AdrianSimionov** [comment]
What if you replace in the text file, before compilation, the line:

    SnmpMibObject pktcMtaDevEnabled.0 Integer 1;

with:

    SnmpMibObject .1.3.6.1.4.1.4491.2.2.1.1.1.7 Integer 1;

I also added a new feature which you should give a try:

    docsis -o -p config_file.bin

Let me know how it works.

**Comment by AdrianSimionov** [comment]
The config file looks a bit weird to me, you also have set in the same NA-config file:

    .1.3.6.1.4.1.7432.1.1.1.6.0

which is the OID for pktcMtaDevEnabled but for EuroPacketCable loads.

You should remove that line.

**Comment by julianeble** [comment]
well that worked, I added that because the wrong value stated before.
Should I use only with OID ?

**Comment by AdrianSimionov** [comment]
It seems that your system is translating pktcMtaDevEnabled to .1.3.6.1.2.1.140.1.1.6

This translation is done by the net-snmp library and not by the docsis utility. And it is done based on the MIB files installed on that specific machine. If you install the correct MIB file, it should do the correct translation. Otherwise, use the numerical value.

**Comment by AdrianSimionov** [comment]
Did it worked when using the numerical OID? Is it safe to close this issue?

**Comment by julianeble** [comment]
Hello Adrian, yes it worked just fine. 
Thank you!
