### ISSUE TITLE
CMTS reject with: INVALID_MODEM_CONFIGURATION_SETTING_FORMAT

### ISSUE THREAD

**Issue by oliemc** [rlaager/docsis#24]
Dear developers,

I just tried to get a FritzBox Cable 6490 provisioned. The CMTS rejects the config file with:

Nov  9 13:30:26: %UBR7200-4-INVALID_MODEM_CONFIGURATION_SETTING_FORMAT

: <133>CMTS[DOCSIS]:<73011700> Invalid Modem Capabilities configuration setting . CM Mac Addr <xxxx.xxxx.xxxx>

Please check the configfile attached. (just remove the .jpg, it's a bin-file) I'm using a cisco UBR7246 with NPE-G2 and MC88V (System image file is "disk2:ubr7200p-jk9su2-mz.122-33.SCD4.BIN")

thanks
Oliver

![avm6490 bin](https://cloud.githubusercontent.com/assets/15730151/11035018/e4a5518a-86ef-11e5-8dc8-96e70502bbc7.jpg)

**Comment by AdrianSimionov** [comment]
Oliver, the config file is encoded correctly. 
Based on the syslog from Cisco, it is complaining about the CM Mac Address from the capabilities list.

This is a field in the REG-REQ packet sent by the CM. It might be that the REG-REQ packet sent by the CM is malformed, or the CMTS thinks is malformed. But without seeing the actual packets it would be close to impossible to know which one is right.

After the REG-REQ there should be another packet, the registration response, sent by the CMTS. In that packet you could see exactly which capability is the CMTS considering mandatory and is malformed or not present.

On Cisco CMTS from what I heard you can do a packet capture, that might help. If you have support from AVM, I would go and ask them how to figure out what is wrong and why is the CMTS is rejecting the modem. I do not know the CLI of the Fritzbox but I think it is Intel based and you might enable some debugging over there and get the packets dumped.

I will keep this open, let us know how it goes.

**Comment by AdrianSimionov** [comment]
Fixed by upgrade on the CMTS, not related to DOCSIS utility.
