### ISSUE TITLE
resolve_oids and NETSNMP_OID_OUTPUT_NUMERIC

### ISSUE THREAD

**Issue by nickhilliard** [rlaager/docsis#39]
the CLI parsing code in main() sets resolve_oids to zero and then calls ```netsnmp_ds_get_boolean(NETSNMP_DS_LIBRARY_ID, NETSNMP_OID_OUTPUT_NUMERIC)``` to force the snmp libs to output in numeric format.  This netsnmp call should be moved to setup_mib_flags(), where all the other snmp flags are set.

**Comment by AdrianSimionov** [comment]
Nick, if you have time feel free to attack this issue. I cannot promise anything until my home lab will be back online which might take some time. I marked it as a feature as it works as it is now, but from an optimization point of view it should be as you mentioned.

Although I did not check the code yet.

**Comment by AdrianSimionov** [comment]
Fixed.
