### ISSUE TITLE
Program will crash if used with invalid parameter

### ISSUE THREAD

**Issue by jcrosso** [rlaager/docsis#48]
By chance I've found that 0.9.9 will segfault if used with a bad first parameter (for example "docsis e").
This can be avoided by adding and extra condition to the last match used by the arg's parser (in docsis.c:430):

    if (argc && encode_docsis)   {

Cheers
JC

**Comment by AdrianSimionov** [comment]
I will have to check if it the only bad parameter which generates a segmentation fault.

Thanks for reporting.
