### ISSUE TITLE
TLV81 encoding issue. DOCSIS 3.1 SSD

### ISSUE THREAD

**Issue by jforhan** [rlaager/docsis#54]
"docsis_symtable.h" has TLV81 as "encode_nothing". It should be able to encode it just fine as a hex string. TLV82 is set to encode as hex.

M-CVC: config file contains a Manufacturer CVC (TLV 32)
Co-CVC: config file contains a Cosigner CVC (TLV 33)
M-chain: config file contains a Manufacturer CVC-chain (TLV 81)
Co-chain: config file contains a Cosigner CVC-chain (TLV 82)
 
32/33 are for legacy modems (DOCSIS 1.x,2.0 & 3.0). For DOCSIS 3.1 a chain of certs is required (TLV81/82) rather than just the MfgCVCData.

The firmware I have is not co-signed so I need to be able to encode TLV81.

Jeff

**Comment by jforhan** [comment]
Confirmed that if I change docsis_symtable.h to "encode_hexstr" for TLV81 and recompile it encodes TLV81 correctly and D3.1 modems upgrade their firmware.

**Comment by rlaager** [comment]
@jforhan, does that commit match the change you made?

**Comment by jforhan** [comment]
Yes, this is the same as the change I made.



[cid:image001.png@01D2A3EF.3A174340]
Jeff Forhan
Network Consulting Engineer
Cable BU
jforhan@cisco.com<mailto:jforhan@cisco.com>
Phone: +1 978 936 1507
Mobile: +1 603 320 3444

Cisco Systems, Inc.
United States
Cisco.com<http://www.cisco.com/>




[hink before you print.]Think before you speak.


This email may contain confidential and privileged material for the sole use of the intended recipient. Any review, use, distribution or disclosure by others is strictly prohibited. If you are not the intended recipient (or authorized to receive for the recipient), please contact the sender by reply email and delete all copies of this message.

For corporate legal information go to:
http://www.cisco.com/web/about/doing_business/legal/cri/index.html

"There are 10 types of people, those that understand binary, and those that don't."

[“hip” , “hip”]
