### ISSUE TITLE
When encoding with empty MIC Key, PacketACE Refuses the file. 

### ISSUE THREAD

**Issue by ioukos** [rlaager/docsis#70]
We use PacketACE to generate files with an empty MIC Key.
Description of the issue :
- I decode a `.md5` file generated form PacketACE with your tool `docsis` to a `.txt` file.
- then I encode the `.txt` back to `.md5` with an empty file as the MIC Key.
- then I import this new `.md5` file to PacketACE, which indicates me that the "Calculated CMTS MIC does not equal tje CMTS MIC in the file".
- IF I set the key to something else (like `foobar`) as the MIC Key File AND in PacketACE there is no error. 

Do you know what could happen here ? Is there an issue because the file is empty ?

Thank you

**Comment by rlaager** [comment]
I have no idea. I’m just a “rescue maintainer”. I know very little about this codebase and haven’t used this tool in some time.

**Comment by qnox81** [comment]
If you want have files encoded without any secret in mic you can try use
mic file with only new line, no other character in it.
It will encode properly and work with CMTSes with no secret configured.

czw., 4 lut 2021, 16:51 użytkownik ioukos <notifications@github.com>
napisał:

**Comment by ioukos** [comment]
I tried to create a "one empty line" file with many techniques but I was not able to success:

- `touch file.key`
- `vim file.key`, then "`a`" (to insert), then `:wq`
- `vim file.key`, then "`a`" (to insert), then "`Enter`" (to insert a second new line), then `:wq`
- `printf "\n" > file.key`
- `printf "\r\n" > file.key`, (even it works with somthing like 'printf "hello\r\n"')

Maybe I can activate DEBUG to show what is read by the encode function. How to do it ?
 
Any idea ?

**Comment by ioukos** [comment]
ok guys everything seems good if I set my MIC key to something else than an empty string.

Moreover I used 3 softwares (including yours and 2 proprietary others) to generate MIC with empty string and I obtain 3 differents results.

Thank you for you work.
