### ISSUE TITLE
Installation to debian_10

### ISSUE THREAD

**Issue by leonardocasimiro** [rlaager/docsis#75]
Walk the next steps, to install this editor in debian 10:
cd /usr/src
apt-get install make
sudo apt-get install m4 bison flex libsnmp-dev
wget http://sourceforge.net/projects/docsis/files/docsis/docsis-0.9.6/docsis-0.9.6.tar.gz
tar -xvzf docsis-0.9.6.tar.gz
cd docsis-0.9.6
A. Type “./configure” to configure the package for your system.
B. Type “make” to compile the package.
C. Type “make install” to install the programs and any data files and more.

best regards.

**Comment by rlaager** [comment]
Can you clarify how it is breaking?

Also, you should probably just be using git master rather than the 0.9.6 tarball.

**Comment by leonardocasimiro** [comment]
hello,

I was just trying to put how to do the installation, since I wasn't capable
and that's how I got it, if you see it opportune, I can delete it.

my intention was to help.
